name: SAKIB-BOT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'
          check-latest: true

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Start SAKIB-BOT
        run: npm start
